### PR TITLE
Implementation of the Projects tab

### PR DESCRIPTION
**Pull request by matthewfritz**
This branch implements both the listing of projects for a given individual (if available) as well as the set of the individual's research interests (if available). Take a look at the Projects tab for me, Nerces, Steve, and John Noga.

~~Selection of multiple filters essentially acts as a set of chained logical `OR` statements.~~
Selection of multiple filters now acts as a set of internal `OR` gates within a filter type and they are chained with external `AND` gates among the various filter types.

**NOTE:** Add the following line to your `.env` file:
`PROJECTS_WEB_SERVICE=https://www.csun.edu/faculty/scholarship/api/`

**NOTE 2 - ELECTRIC BOOGALOO:** Run `npm install` or `yarn install` since the dependency for Moment.js has been added.

### CODE REVIEW

**Review by nercesk — DISMISSED** [review]

**Comment by matthewfritz** [comment]
@nercesk I dismissed the review since I added another commit to make things open in a new window and also added the missing search links to the research interest badges.

**Comment by matthewfritz** [comment]
@nercesk @andrewMETALAB The filters have been switched from only OR gates to internal ORs chained with external ANDs.

**Review by nercesk — DISMISSED** [review]

**Comment by matthewfritz** [comment]
@nercesk @andrewMETALAB Okay, that was the last commit, I swear.

**Review by nercesk — APPROVED** [review]

**Review by andrewMETALAB — APPROVED** [review]
10/10, would recommend 👍

**Pull request merged**
